---
new_page_extension: md
auto_deploy: false
admin_path: "/forestry/"
webhook_url: source/admin/forestry
sections:
- type: directory
  path: source/_categories
  label: " Categories"
  create: all
  match: "**/*"
- type: directory
  path: source/_tags
  label: Tags
  create: all
  match: "**/*"
- type: directory
  path: source/_posts
  label: Posts
  create: all
  match: "**/*"
- type: heading
  label: Blog
- type: directory
  path: source/_pages
  label: Pages
  create: all
  match: "**/*"
upload_dir: source/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
